### ISSUE TITLE
Infinite loop when parsing BidRequest json with unknown extensions

### ISSUE THREAD

**Issue by pawelkowalskicw** [google/openrtb#34]
Omitting unknown extensions seems to be  promising feature , but it looks like there is some bug there. (0.8.2 used). When I try to parse following BidRequest JSON with some extensions reader gets into infinite loop.
Could you please try and advice what's wrong:
```json
{
  "app": {
    "cat": ["IAB20"],
    "domain": "microsoft.com",
    "id": "65848430",
    "name": "Windows_ROW_300x50",
    "publisher": {"id": "923881016"}
  },
  "at": 2,
  "device": {
    "connectiontype": 0,
    "devicetype": 1,
    "dnt": 0,
    "geo": {
      "country": "IND",
      "lat": 18.975,
      "lon": 72.8258,
      "type": 1
    },
    "ip": "114.79.158.227",
    "js": 0,
    "make": "Generic",
    "model": "Windows Phone 8",
    "os": "Windows Phone OS",
    "osv": "8",
    "ua": "Windows Phone Ad Client/6.2.960.0 (Silverlight; MS_ORMMA_1_0; Windows Phone OS 8.10.14226.0; Microsoft; RM-1090_1001)"
  },
  "ext": {
    "carriername": "unknown - probably WLAN",
    "coppa": 0,
    "operaminibrowser": 0,
    "udi": {"wpid": "1083402449863976572"}
  },
  "id": "Ax1jZdSvJk",
  "imp": [
    {
      "banner": {
        "battr": [
          1,
          3,
          5,
          8,
          9
        ],
        "btype": [
          1,
          3
        ],
        "h": 50,
        "mimes": [
          "image/gif",
          "image/jpeg",
          "image/png"
        ],
        "w": 300
      },
      "displaymanager": "SOMA",
      "id": "1",
      "instl": 0
    }
  ],
  "user": {}
}
```

**Comment by pawelkowalskicw** [comment]
Additionally I noticed when I registered at least one extension Reader (even dummy - that reads nothing) it avoided loop, however in this particular case it fails with exception:
```java
com.google.protobuf.UninitializedMessageException: Message missing required fields: id
	at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:372)
	at com.google.openrtb.OpenRtb$BidRequest$Builder.build(OpenRtb.java:50992)
	at com.google.openrtb.json.OpenRtbJsonReader.readBidRequest(OpenRtbJsonReader.java:119)
```
due to the last "udi" extensions which is nested and nothig after extension part is read by parser.
In case when there are only scalar extensions it works fine. Try with the same case mentioned previously but without "udi"

**Comment by opinali** [comment]
Thanks for the report, this definitely looks like a bug -- apparently the new unit tests that cover this stuff weren't good enough :( gonna fix this asap.

**Comment by opinali** [comment]
All fixed in master, can you test to confirm?

**Comment by pawelkowalskicw** [comment]
Thanks for you quick replay , I have tested it and it is partially fixed. I mean there is no more infinite loop observed when there are unknown extensions, but there is still issue  with reading non-scalar extensions as last one. It causes end of  reading (before id is read and everything further) and again I got  
```java
com.google.protobuf.UninitializedMessageException: Message missing required fields: id
    at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:372)
    at com.google.openrtb.OpenRtb$BidRequest$Builder.build(OpenRtb.java:50992)
    at com.google.openrtb.json.OpenRtbJsonReader.readBidRequest(OpenRtbJsonReader.java:119)
```
I observed this happens only if non-scalar is last one as in the example provided by me in first post - the "udi" one. If you shuffle order of extensions and "udi" is not last one it works fine

**Comment by opinali** [comment]
Oh well another corner case... think I've got it right now, please try again.

**Comment by pawelkowalskicw** [comment]
It works now  :) Thanks for quick fix!

BTW Could you please  add *.proto files to jar file when releasing openrtb?  The reason is because  in order to generate extensions from my .proto files there is required to include openrtb*.proto files and also add dependency to openrtb. So this is not convenient and it may lead to incompatibility between generated extensions classes and openrtb classes if one forgot to synch them when updating openrtb in project.
What I wanted to do to is to extract these *.proto from dependency jar before generating my and this way I would have compatibility between  extensions generated bindings and openrtb generated bindings classes guaranteed and all this stuff automated. 
Or maybe you can suggest something else?

**Comment by opinali** [comment]
Great! Now for the proto... good idea except that it would be OK to put the proto files in the source-jar, not in the main jar. Would that help you?

(Alternatively you can use the download-maven-plugin to fetch the proto directly from github.)

**Comment by pawelkowalskicw** [comment]
Yes, source-jar are OK as long as they are in maven repo.
Download-maven-plugin also would work if there would be easy to match url to dependency version declared in pom i.e. branch,tag .
Anyway looking forward for next release :)

**Comment by opinali** [comment]
Good, released then!
